config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  with_dev_auth =
    lambda do |app|
      Rack::Builder.new do
        use Rack::Auth::Basic do |username, password|
          ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest("admin")) &
            ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV.fetch("ADMIN_PASSWORD")))
        end
        run app
      end
    end

  mount with_dev_auth.call(Sidekiq::Web), at: "sidekiq"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'private_sessions#destroy'
  get 'register', to: 'user#new'
  post 'register', to: 'user#create'
  get '/order', to: 'order#index'

  resources :passwords
  get "password/forgot", to: 'password#forgot'
  post 'password/forgot', to: 'password#forgot'
  post 'password/reset', to: 'password#reset'
  resources :news_articles
  resources :indicators
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # GET /
  root to: 'home#index'

  # GET /about
  get '/about', to: 'about#index'

  # paths for coin
  resources :coin
  get '/chart_data/avg', to: "coin#chart_avg_data"
  get '/chart_data/ask', to: "coin#chart_ask_data"
  get '/chart_data/bid', to: "coin#chart_bid_data"
  get '/chart_data/price', to: "coin#chart_price_data"

  resources :indicator
  get '/indicator/data', to: "indicator#get_data"


  # private user routes
  get '/account', to: 'user#show'
  get '/account/edit', to: 'user#edit'
  post '/user/edit', to: 'user#update'

  # strategies
  get '/strategies/library', to: 'strategies#show'
  get '/strategies/new', to: 'strategies#new'
  post 'strategies/new', to: 'strategies#create'
  post '/strategies/add_card', to: 'strategies#add_card'
  post '/strategies/delete/:id', to: 'strategies#delete'
  get '/strategies/edit/:id', to: 'strategies#edit'
  post '/strategies/edit/:id', to: 'strategies#update'
  post '/strategies/execute/:id', to: 'strategies#manual_execute'
  post '/strategies/toggle/:id', to: 'strategies#toggle'

  # orders
  post '/order', to: 'order#order'

  get '*path' => redirect('/')
end

app/views/shared/_lock_modal.html.erb
<% unless safe_user? %>
  <div class='overlay'></div>
  <div class='card shadow-lg lock gradient-custom'>
    <div class='card-body'>
      <i class="fas fa-lock fa-10x"></i>
      <div class='pt-5'>
        You cannot access this page since you have not registered your BinanceUS account with us.
      </div>
      <div class='pt-5'>
        <%= link_to "Update your account", '/account/edit', class: 'btn btn-lg btn-secondary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<% if logged_in? %>
  <%= render 'shared/private_nav' %>
<% else %>
  <%= render 'shared/public_nav' %>
<% end %>

app/views/shared/_private_nav.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <a class="navbar-brand mt-2 mt-lg-0" href="/">
        <%= image_tag "nav_logo.png", alt: "logo", loading: 'lazy' %>
      </a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to coin_index_path, class: "nav-link" do%>
            Supported Cryptos
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to '/about', class: "nav-link" do%>
            About
          <% end %>
        </li>
        <li class="nav-item dropdown me-3 me-lg-1" id="workspaceDropdownLink">
          <a
            class="nav-link dropdown-toggle hidden-arrow"
            href="#"
            id="workspaceDropdown"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
            style="height:110%"
          >
            Workspace
          </a>
          <ul
            class="dropdown-menu dropdown-menu-end dropdown-menu-dark"
            aria-labelledby="workspaceDropdown"
            id="workspaceList"
          >
            <li>
              <%= link_to 'Strategies Creation', '/strategies/new' , class: 'dropdown-item' %>
            </li>
            <li>
              <%= link_to 'Strategies Library', '/strategies/library', class: 'dropdown-item' %>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to '/order', class: "nav-link" do%>
            Order Crypto
          <% end %>
        </li>
      </ul>
    </div>
    <div class="d-flex align-items-center">
      <div class="container-fluid">
        <%= form_tag request.path, method: "GET", class: "d-flex input-group w-auto", id: 'search_form' do %>
          <%= text_field_tag :search_param, params[:search_param], 
            placeholder: "Search this page...", class: "form-control rounded", type: "search" %>
          <span class="input-group-text text-white border-0" id="search-addon">
            <%= link_to request.path, onclick: "$('#search_form').submit()"  do %>
              <i class="bi bi-search" style="color: white;"></i>
            <% end %>
          </span>
        <% end %>
      </div>
      <%= render 'partials/user_icon' %>
  </div>
</nav>

app/views/shared/_public_nav.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <a class="navbar-brand mt-2 mt-lg-0" href="/">
        <%= image_tag "nav_logo.png", alt: "logo", loading: 'lazy' %>
      </a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to '/about', class: "nav-link" do%>
            About
          <% end %>
        </li>
      </ul>
    </div>
    <div class="pub-nav-buttons">
      <%= link_to 'Sign-in', '/login', class: 'btn btn-primary' %>
      <%= link_to 'Don\'t have an account? Sign up', '/register', class: 'btn btn-primary' %>
  </div>
</nav>